### PR TITLE
Translated in Italian

### PR DESCRIPTION
**Pull request by Peppuz**
Added json files to themes admin and store locales

### CODE REVIEW

**Comment by channingbox** [comment]
we have json file for each locale and each project section.

Dashboard: https://github.com/cezerin/cezerin/tree/master/locales/admin
Store: https://github.com/cezerin/cezerin/tree/master/locales/store
Theme: https://github.com/cezerin/cezerin/tree/master/theme/locales
https://github.com/cezerin/cezerin/tree/master/theme/config

**Comment by Peppuz** [comment]
I made the first 3, 
i guess is missing the ```setting_schema_it.json``` file, right?

**Comment by channingbox** [comment]
I think so

**Comment by Peppuz** [comment]
@channingbox Check this out!

**Comment by channingbox** [comment]
@restmount

**Comment by channingbox** [comment]
before merged ,u can edit it.

**Comment by Peppuz** [comment]
Ok I’ll make a single commit, wait next comment. 
Telegram

**Comment by sonufrienko** [comment]
@Peppuz 
Thanks for your contribution.

**Comment by Peppuz** [comment]
Appreciate your work guys! <3

**Pull request merged**
