### PR TITLE
Remove same key for locale files

### PR DESCRIPTION
**Pull request by w-site**
Remove same key for locale files. You have already key for "products_discontinued" above

### CODE REVIEW

**Comment by mrhut10** [comment]
this makes sense and should have someone look at straight away,
have you had any feedback @w-site

**Comment by w-site** [comment]
@mrhut10 no, nobody take a look for pull request I think (

**Comment by sonufrienko** [comment]
@w-site 
**products_discontinued** is used and can't be removed.

One of file where is used:
/src/admin/client/modules/products/list/components/item.js

**Comment by w-site** [comment]
@sonufrienko Lol, if you will check pull request in time than you will be able to see that this kay was duplicated, this is why this PR was created.
image

**Pull request closed without merging**
